### ISSUE TITLE
feature request: handling spacebar when window is closed

### ISSUE THREAD

**Issue by privatenumber** [wulkano/Plug#16]
I have a habit of <kbd>Command</kbd>+<kbd>tab</kbd>ing to the app playing music and pressing <kbd>space</kbd> to pause. I believe iTunes supports this, and Spotify doesn't, but the window opens every time I <kbd>Command</kbd>+<kbd>tab</kbd> into it to catch and handle the <kbd>space</kbd>.

Can Plug either handle <kbd>space</kbd> to pause while the window is closed, or make the window open whenever <kbd>Command</kbd>+<kbd>tab</kbd>ing to the app?

**Comment by sindresorhus** [comment]
This is now out in the App Store. Just go to https://apps.apple.com/no/app/plug-for-hype-machine/id1514182074?mt=12 and click "Update".

**Comment by privatenumber** [comment]
Flawless! Thanks @sindresorhus 🙌

**Comment by sindresorhus** [comment]
Don't forget to rate Plug on the App Store 🙏
