### ISSUE TITLE
Getting `APIError`. Is this app dead now?

### ISSUE THREAD

**Issue by chadparker** [wulkano/Plug#25]
I haven't used it for a while but wanted some variety in my music so I launched it and get this API message:

![Screenshot 2024-05-15 at 8 46 04 AM](https://github.com/wulkano/Plug/assets/438307/d3857aa3-8bc8-4cc4-99e9-9182bc16499d)

Is this app dead now?

**Comment by sindresorhus** [comment]
It may have been a temporary HypeMachine issue. It works fine for me now.

**Comment by chadparker** [comment]
Thanks! It was a couple-week period where it wasn't working so I uninstalled it. I just reinstalled it from the app store and it's working just fine now.
