### ISSUE TITLE
Create new icon for macOS 11

### ISSUE THREAD

**Issue by sindresorhus** [wulkano/Plug#5]
New icon style: https://twitter.com/jeremyburge/status/1277196845060624385

Template here: https://developer.apple.com/design/resources/#macos-apps

**Comment by alexmarchant** [comment]
Can get you the original sketch file

**Comment by sindresorhus** [comment]
That would be great.

**Comment by alexmarchant** [comment]
https://www.dropbox.com/s/oaosv50xu4rtp5e/Plug.zip?dl=0

**Comment by alexmarchant** [comment]
[Plug-Icon.sketch.zip](https://github.com/wulkano/Plug/files/4854452/Plug-Icon.sketch.zip)
