### ISSUE TITLE
Use native titlebar and add divider

### ISSUE THREAD

**Issue by skllcrn** [wulkano/Plug#7]
The titlebar should be distinct from the sidebar and content areas, using its native styles. Additionally, the content and sidebar should be separated by a dark divider line: 
![image](https://user-images.githubusercontent.com/8440026/94632066-ef376880-02c9-11eb-8075-c4095e6d0079.png)

**Comment by sindresorhus** [comment]
We should also switch out the custom back buttons with something native:

![image](https://user-images.githubusercontent.com/170270/94632039-df1f8900-02c9-11eb-8a4a-0d26569bad20.png)

**Comment by sindresorhus** [comment]
Fixed by https://github.com/wulkano/Plug/commit/c5d93aa073368f03873b754b55bf75c138946e1d
